HS_CHAPTER_TO_INDUSTRY = {
    "01": "Agriculture", "02": "Agriculture", "03": "Agriculture",
    "04": "Food & Dairy", "05": "Agriculture",
    "06": "Agriculture", "07": "Agriculture", "08": "Agriculture",
    "09": "Food & Beverage", "10": "Agriculture", "11": "Food Processing",
    "12": "Agriculture", "13": "Pharmaceuticals", "14": "Agriculture",
    "15": "Food & Beverage", "16": "Food Processing",
    "17": "Food & Beverage", "18": "Food & Beverage",
    "19": "Food Processing", "20": "Food Processing",
    "21": "Food & Beverage", "22": "Food & Beverage",
    "23": "Animal Feed", "24": "Tobacco",
    "25": "Mining & Construction", "26": "Mining",
    "27": "Energy & Petroleum", "28": "Chemicals",
    "29": "Chemicals", "30": "Pharmaceuticals",
    "31": "Agriculture (Fertilizers)", "32": "Chemicals",
    "33": "Cosmetics", "34": "Chemicals",
    "35": "Chemicals", "36": "Chemicals",
    "37": "Photography", "38": "Chemicals",
    "39": "Plastics", "40": "Rubber",
    "41": "Leather", "42": "Leather Goods",
    "43": "Fur & Leather", "44": "Wood & Furniture",
    "45": "Wood", "46": "Wood",
    "47": "Paper & Pulp", "48": "Paper & Packaging",
    "49": "Publishing & Print", "50": "Textiles",
    "51": "Textiles", "52": "Textiles",
    "53": "Textiles", "54": "Textiles",
    "55": "Textiles", "56": "Textiles",
    "57": "Textiles", "58": "Textiles",
    "59": "Textiles", "60": "Textiles",
    "61": "Apparel", "62": "Apparel",
    "63": "Apparel & Home Textiles", "64": "Footwear",
    "65": "Apparel", "66": "Apparel",
    "67": "Apparel", "68": "Construction Materials",
    "69": "Ceramics", "70": "Glass",
    "71": "Jewellery & Gems", "72": "Steel & Iron",
    "73": "Steel Products", "74": "Copper",
    "75": "Nickel", "76": "Aluminium",
    "77": "Metals", "78": "Lead",
    "79": "Zinc", "80": "Tin",
    "81": "Metals", "82": "Tools & Hardware",
    "83": "Hardware", "84": "Industrial Machinery",
    "85": "Electronics & Electrical", "86": "Rail Transport",
    "87": "Automotive", "88": "Aerospace",
    "89": "Shipbuilding", "90": "Medical & Optical Instruments",
    "91": "Clocks & Watches", "92": "Musical Instruments",
    "93": "Arms & Defence", "94": "Furniture",
    "95": "Toys & Sports", "96": "Miscellaneous Manufacturing",
    "97": "Art & Antiques", "99": "Special Transactions",
}

def get_industry_from_hs(hs_code: str) -> str:
    try:
        chapter = str(hs_code).zfill(6)[:2]
        return HS_CHAPTER_TO_INDUSTRY.get(chapter, "Other")
    except Exception:
        return "Other"